export const ADD_STAFF = 'ADD_STAFF';
export const STAFF_LOADING = 'STAFF_LOADING';
export const STAFF_FAILED = 'STAFF_FAILED';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';

export const ADD_STAFFSALARY = 'ADD_STAFFSALARY';
export const STAFFSALARY_LOADING = 'STAFFSALARY_LOADING';
export const STAFFSALARY_FAILED = 'STAFFSALARY_FAILED';

export const ADD_STAFFINDEPT = 'ADD_STAFFINDEPT';
export const STAFFINDEPT_LOADING = 'STAFFINDEPT_LOADING';
export const STAFFINDEPT_FAILED = 'STAFFINDEPT_FAILED';
